---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: cert-manager
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: external-dns
  valuesFile: https://github.llamasoft.com/devops/nonprod-configs/tree/ltst_env/aws/ltst/external-dns/values.yaml
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: external-dns
    version: 2.11.0
