---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: m3test
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: grafana
  valuesFile: https://github.llamasoft.com/devops/nonprod-configs/blob/master/aws/loadtesting/grafana/values.yaml
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: grafana
    version: 4.0.3
