---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: influxdb
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: influxdb
  valuesFile: https://github.llamasoft.com/devops/nonprod-configs/blob/ltst_env/aws/ltst/influxdb/values.yaml
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: influxdb
    version: 4.0.3
