---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: nginx-ingress
  valuesFile: https://github.llamasoft.com/devops/nonprod-configs/blob/ltst_env/aws/ltst/nginx-ingress/values.yaml
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nginx-ingress
    version: 1.26.1
